language: python
# blocklist
branches:
  except:
  - dev
# safelist
branches:
  only:
  - master
sudo: required
services:
  - docker
before_install:
  - docker pull thomaszastrow/fedora-commons
  - docker run -d=true -p 8080:8080 -t -i thomaszastrow/fedora-commons /bin/bash
  - echo "import time; time.sleep(60)" | python
  - cp tests/localsettings.py.template tests/localsettings.py
python:
  - "3.5"
# command to install dependencies
install: "pip3 install -e ."
# command to run tests
script: pytest