language: python
# blocklist
branches:
  except:
  - dev
# safelist
branches:
  only:
  - master
sudo: required
services:
  - docker
before_install:
  - docker pull yinlinchen/fcrepo4-docker
  - docker run -it -p 8080:8080 -p 9080:9080 -d yinlinchen/fcrepo4-docker:4.7.3
  - echo "import time; time.sleep(300)" | python
  - cp tests/localsettings.py.template tests/localsettings.py
python:
  - "3.5"
# command to install dependencies
install: "pip3 install -e ."
# command to run tests
script: pytest