language: python
# blocklist
branches:
  except:
  - dev
# safelist
branches:
  only:
  - master
sudo: required
services:
  - docker
before_install:
  - docker pull ghukill/fc4
  - docker run -d -i -t -p 8080:8080 ghukill/fc4
  - echo "import time; time.sleep(20)" | python
  - cp tests/localsettings.py.template tests/localsettings.py
python:
  - "3.5"
# command to install dependencies
install: "pip3 install -e ."
# command to run tests
script: pytest