language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip
# blocklist
branches:
  except:
  - dev
# safelist
branches:
  only:
  - master
services:
  - docker
before_install:
  - docker pull ghukill/fc4
  - docker run -d -i -t -p 8080:8080 ghukill/fc4
  - echo "import time; time.sleep(20)" | python
  - cp tests/localsettings.py.template tests/localsettings.py
# command to install dependencies
install:
  - pip3 install -r requirements*
  - pip3 install -e .
# command to run tests
script: pytest
